### ISSUE TITLE
`App.css` needs re-placement

### ISSUE THREAD

**Issue by Hakeemmidan** [michaeltorres1/WiRR#23]
We need to place `App.css` in the `stylesheets` folder for better file structure.
I will not change its location since I know that some of you are currently working on it. If you are working on it, please assign yourself to this issue, and change its location in your next pull request.

Cheers,
Hakeem

**Comment by michaeltorres1** [comment]
I agree with @Hakeemmidan. We need to make sure that the the css files are properly organized. We should try to get this to work once we are finalizing our project according to our group discussion.

**Comment by michaeltorres1** [comment]
Because there are some files that have been changed / refactored let's not try to solve this issue until the end to avoid confusion amongst our team. We should be all able to work on this once we have or file structure and file names organized as we want them to be. Also, leaving this for the end will probably be a good idea to avoid merge conflicts.

Thanks!

**Comment by Hakeemmidan** [comment]
`app.css` is now placed in `client/src/stylesheets`
