### ISSUE TITLE
Redux integration and passing info to `article_show.jsx`'s charts

### ISSUE THREAD

**Issue by Hakeemmidan** [michaeltorres1/WiRR#31]
We need to add a bit of Redux for better front end state management in the `ArticleShow` React component. This is going to make things a lot cleaner since we will not need to import functions in charts every time we need them.

Moreover, what we are currently doing is costly in terms of time complexity and computing power because it requires an API call every time `visitPage(pageUrl)` is invoked. We could fix this by including `visitPage(pageUrl)` in the container that is holding all charts (`ArticleShow`) and pass on the information that each chart needs respectively. 

Cheers,
Hakeem

**Comment by michaeltorres1** [comment]
I agree with you @Hakeemmidan. The addition of the Redux will probably be part of the code refactoring as well so once this issue is closed we should double check any other unnecessary code and get rid of it or optimize any code that lacks in performance. Because I helped in the code refactoring for this I would go ahead and assign myself to this issue as well. You contributed the most to the Redux integration so I will not add myself to the pull request that closes this issue.

Thanks for having brought this up. Our code is easier to manage now!
